name: Rust Checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  RUSTFLAGS: "-D warnings"

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x8-with-cache
      - nscloud-cache-tag-bullet-exchange-interface
      - nscloud-cache-size-50gb
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Format check (nightly)
        run: cargo +nightly fmt --all -- --config-path rustfmt.nightly.toml --check
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Check
        run: cargo check
